services:

  srv-redis:
    # Use the redis:alpine image from Docker Hub
    image: redis:alpine
    container_name: srv-redis
    volumes:
      - redis_data:/data
    networks:
      - internal-network
    # up at docker startup
    restart: unless-stopped

  app:
    build:
      context: .
      args:
        - PORT=${PORT}
    container_name: ${PRJ_NAME}
    image: ${PRJ_NAME}-image
    ports:
      - "$PORT:$PORT"
    volumes:
      - ./app:/app
    environment:
      - PRJ_NAME
      - CONFIG_DIR
      - PORT
    networks:
      - global_network
      - internal-network
    restart: unless-stopped

volumes:
  redis_data:

networks:
  global_network:
    external: true
  internal-network:
    driver: bridge